version: '3'

services:
  mysql:
    image: 'mysql:latest'
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "9910:3306"
    environment:
      - MYSQL_DATABASE=douyindb
      - MYSQL_USER=readygo
      - MYSQL_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  redis:
    image: 'redis:latest'
    container_name: douyin_redis
    command: redis-server --requirepass 123456
    ports:
      - "26379:6379"